EPP-52 Setting up dev environment
UKHomeOffice/explosives-precursors-poisons pull request #1
Opened 2024-12-03 12:17 UTC by MikeMaratheftis

## What? 
[EPP-52](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-52) - Create dev environment 

## Why? 

## How? 

## Testing?
Tested on local machine 

## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [x] I have created a JIRA number for my branch
- [x] I have created a JIRA number for my commit
- [x] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [x] Ensure drone builds are green especially tests
- [x] I will squash the commits before merging

2024-12-03 16:50 UTC, PaolaDMadd-Pro requested changes
Good work, I added small suggestions, that won't preclude the merging.
@william-gu-hof

2024-12-03 16:50 UTC, PaolaDMadd-Pro commented on package.json
> +  "name": "hof-epp-form",
Please verify if the name of the app needs to reflect the name of the git repository or hosting platform name

2024-12-03 16:50 UTC, PaolaDMadd-Pro commented on package.json
> +  "description": "Simple standard form made using HOF",
```suggestion
  "description": "Explosive precursors and poisons within top-level forms",
```

2024-12-04 10:21 UTC, MikeMaratheftis commented on config.js
> +  PRETTY_DATE_FORMAT: 'Do MMMM YYYY',
The correct format is 'DD MMMM YYYY' 

Good spot :)

2024-12-04 10:48 UTC, PaolaDMadd-Pro approved these changes
looks good to me

2024-12-04 10:55 UTC, merged