EPP39 Other nationalities page [ WIP ]
UKHomeOffice/explosives-precursors-poisons pull request #7
Opened 2024-12-19 12:54 UTC by vivekkumar-ho

## What? 
## Why? 
## How? 
## Testing?
## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ ] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ ] I have created a JIRA number for my branch
- [ ] I have created a JIRA number for my commit
- [ ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [ ] Ensure drone builds are green especially tests
- [ ] I will squash the commits before merging

2025-01-10 11:36 UTC, MikeMaratheftis approved these changes
Looks good

2025-01-14 10:28 UTC, TemitopeAyokuHO requested changes

2025-01-14 10:28 UTC, TemitopeAyokuHO commented on apps/epp-new/translations/src/en/pages.json
> +  "enter-license-number": {
@vivekkumar-ho  This should be changed to "license-number"

2025-01-14 10:28 UTC, TemitopeAyokuHO commented on apps/epp-new/translations/src/en/pages.json
> +        "header": "Applicant Details"
This should be reverted ass per Figma it's lowercase d

2025-01-14 10:50 UTC, vivekkumar-ho commented on apps/epp-new/behaviours/filter-countries.js
> +  };
new and renew pages are common in the new folder itself (apart from licence number page) so this will be reused anyway.

2025-01-14 10:53 UTC, vivekkumar-ho commented on apps/epp-new/translations/src/en/pages.json
> +  "enter-license-number": {
Looks like this is due to conflict from master. I've updated it now.

2025-01-14 10:53 UTC, vivekkumar-ho commented on apps/epp-new/translations/src/en/pages.json
> +        "header": "Applicant Details"
Same as above, updated now.

2025-01-14 16:26 UTC, TemitopeAyokuHO approved these changes
Look good to me

2025-01-16 12:05 UTC, merged